export const projectsData = [
  { name: "TSMC 台積電全球研發中心", category: "企業總部大樓", domain: "tsmc.com" },
  { name: "TSMC 台積電晶圓二十廠", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電先進封測三廠", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電先進封測六廠", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電中科新人訓練中心", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電南科晶圓P5廠辦", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電南科晶圓14廠 P3", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電竹科晶圓12廠", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電CP03測試廠", category: "商用空間", domain: "tsmc.com" },
  { name: "TSMC 台積電中科晶圓廠辦 II", category: "商用空間", domain: "tsmc.com" },
  { name: "Qualcomm 大樓", category: "企業辦公室", domain: "qualcomm.com" },
  { name: "LINE Taiwan Office", category: "企業辦公室", domain: "line.me" },
  { name: "瑞健總部大樓", category: "企業總部大樓", domain: "shl-medical.com" },
  { name: "惠榮科技總部大樓", category: "企業總部大樓", domain: "siliconmotion.com" },
  { name: "笙科電子台元辦公室", category: "企業辦公室", domain: "amiccom.com.tw" },
  { name: "致茂電子總部", category: "企業總部大樓", domain: "chromaate.com" },
  { name: "城邦南港新辦公室", category: "企業辦公室", domain: "cite.com.tw" },
  { name: "南茂科技", category: "企業辦公室", domain: "chipmos.com" },
  { name: "采鈺科技龍科廠辦公室", category: "企業辦公室", domain: "viseraseotech.com" },
  { name: "松川精密嘉義廠", category: "商用空間", domain: "songchuan.com" },
  { name: "立信機構企業總部", category: "企業總部大樓", domain: null },
  { name: "玉山銀行總行", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行第二總部大樓 數位夢工場", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行第二總部大樓", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行科技大樓 辦公空間", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行行史館 - 玉山紀事", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行人力發展中心", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行 高雄旗艦大樓", category: "金融業", domain: "esunbank.com.tw" },
  { name: "日月光中壢廠 K棟 / M棟", category: "商用空間", domain: "asecg.com" },
  { name: "中鋼集團總部大樓", category: "企業總部大樓", domain: "csc.com.tw" },
  { name: "中華機械關渡新廠", category: "商用空間", domain: null },
  { name: "中華賓士關渡展示中心", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "中華賓士高雄展示中心-AMG展廳", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "中華賓士桃園展示中心", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "中華賓士河南路展示中心", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "中華賓士台中展示中心-AMG展廳", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "中華賓士中港路展示中心", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "Alliance Bernstein", category: "金融業", domain: "alliancebernstein.com" },
  { name: "Applied Materials GTLC", category: "企業辦公室", domain: "appliedmaterials.com" },
  { name: "Applied Materials Linkou", category: "企業辦公室", domain: "appliedmaterials.com" },
  { name: "Applied Materials Taiwan", category: "企業辦公室", domain: "appliedmaterials.com" },
  { name: "Autodesk", category: "企業辦公室", domain: "autodesk.com" },
  { name: "BlackRock", category: "金融業", domain: "blackrock.com" },
  { name: "CIGNA", category: "金融業", domain: "cigna.com.tw" },
  { name: "CIGNA KH MinChu", category: "金融業", domain: "cigna.com.tw" },
  { name: "Chubb", category: "金融業", domain: "chubb.com" },
  { name: "Cisco", category: "企業辦公室", domain: "cisco.com" },
  { name: "Credit Suisse", category: "金融業", domain: "credit-suisse.com" },
  { name: "DBS星展銀行內湖辦公室", category: "金融業", domain: "dbs.com" },
  { name: "DELL", category: "企業辦公室", domain: "dell.com" },
  { name: "DeFITs Capital 台北辦公室", category: "金融業", domain: null },
  { name: "Diageo", category: "企業辦公室", domain: "diageo.com" },
  { name: "Gartner", category: "企業辦公室", domain: "gartner.com" },
  { name: "Google", category: "企業辦公室", domain: "google.com" },
  { name: "Hewlett Packard Enterprise", category: "企業辦公室", domain: "hpe.com" },
  { name: "IBM CFC", category: "企業辦公室", domain: "ibm.com" },
  { name: "Intel", category: "企業辦公室", domain: "intel.com" },
  { name: "JP morgan", category: "金融業", domain: "jpmorgan.com" },
  { name: "JnJ", category: "企業辦公室", domain: "jnj.com" },
  { name: "Merck", category: "企業辦公室", domain: "merck.com" },
  { name: "Natixis", category: "金融業", domain: "natixis.com" },
  { name: "Neuberger Berman", category: "金融業", domain: "nb.com" },
  { name: "Nike", category: "企業辦公室", domain: "nike.com" },
  { name: "P & G", category: "企業辦公室", domain: "pg.com" },
  { name: "PRA", category: "企業辦公室", domain: null },
  { name: "Parexel International", category: "企業辦公室", domain: "parexel.com" },
  { name: "Qualcomm CTIP", category: "企業辦公室", domain: "qualcomm.com" },
  { name: "Qualcomm NeiHu", category: "企業辦公室", domain: "qualcomm.com" },
  { name: "Sanofi", category: "企業辦公室", domain: "sanofi.com" },
  { name: "State Street Bank", category: "金融業", domain: "statestreet.com" },
  { name: "Syneos", category: "企業辦公室", domain: "syneoshealth.com" },
  { name: "Syneos Health Taipei", category: "企業辦公室", domain: "syneoshealth.com" },
  { name: "UBS", category: "金融業", domain: "ubs.com" },
  { name: "Warner Bros Discovery", category: "企業辦公室", domain: "wbd.com" },
  { name: "WorldQuant", category: "企業辦公室", domain: "worldquant.com" },
  { name: "YOUNG LIVING台北辦公室", category: "企業辦公室", domain: "youngliving.com" },
  { name: "台北101 尊榮俱樂部", category: "商用空間", domain: "taipei-101.com.tw" },
  { name: "台北君悅酒店1-2樓", category: "商用空間", domain: "hyatt.com" },
  { name: "台灣愛丁頓寰盛辦公室", category: "企業辦公室", domain: "edrington.com" },
  { name: "喜瑪拉雅基金會", category: "商用空間", domain: null },
  { name: "大元建築事務所", category: "商用空間", domain: "artech-inc.com" },
  { name: "大瓏企業 展示廳", category: "商用空間", domain: null },
  { name: "戴姆勒台北辦公室", category: "企業辦公室", domain: "mercedes-benz.com.tw" },
  { name: "日月光中壢廠", category: "商用空間", domain: "asecg.com" },
  { name: "明門實業汐止辦公室", category: "企業辦公室", domain: "wonderland.com.tw" },
  { name: "玉山銀行創意中心二期", category: "金融業", domain: "esunbank.com.tw" },
  { name: "華南銀行新形象 南松山示範分行", category: "金融業", domain: "hncb.com.tw" },
  { name: "鴻霖全球運輸公司", category: "商用空間", domain: "morrisonexpress.com" },
  { name: "上海商銀 行史館", category: "金融業", domain: "scsb.com.tw" },
  { name: "YOUNG LIVING台中辦公室", category: "企業辦公室", domain: "youngliving.com" },
  { name: "TSMC台積創新館", category: "商用空間", domain: "tsmc.com" },
  { name: "Sony Store 漢神巨蛋店", category: "商用空間", domain: "sony.com.tw" },
  { name: "Sony Store 台北101 B1", category: "商用空間", domain: "sony.com.tw" },
  { name: "聯立賓士新竹展示中心", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "桃園大溪威斯汀酒店", category: "商用空間", domain: "starwoodhotels.com" },
  { name: "美麗網求高爾夫華鄉村俱樂部", category: "商用空間", domain: null },
  { name: "宏其婦幼醫院", category: "商用空間", domain: "hungchi.com.tw" },
  { name: "老爺行旅宜蘭傳藝中餐廳", category: "商用空間", domain: "hotelroyal.com.tw" },
  { name: "台北101 88樓高空場域", category: "商用空間", domain: "taipei-101.com.tw" },
  { name: "中華賓士內湖展廳", category: "商用空間", domain: "mercedes-benz.com.tw" },
  { name: "三立電視-B1F藝能中心", category: "企業辦公室", domain: "setn.com" },
  { name: "三立電視-創意中心", category: "企業辦公室", domain: "setn.com" },
  { name: "三立電視-行動媒體辦公室", category: "企業辦公室", domain: "setn.com" },
  { name: "DBS星展銀行 JoySpace 辦公空間", category: "金融業", domain: "dbs.com" },
  { name: "匯豐銀行天母分行", category: "金融業", domain: "hsbc.com.tw" },
  { name: "凱基銀行南京東路營業部", category: "金融業", domain: "kgibank.com.tw" },
  { name: "第一銀行 高資產理財旗艦中心", category: "金融業", domain: "firstbank.com.tw" },
  { name: "金融研訓院", category: "金融業", domain: "tabf.org.tw" },
  { name: "花旗銀行桃園分行", category: "金融業", domain: "citibank.com.tw" },
  { name: "花旗銀行內湖分行", category: "金融業", domain: "citibank.com.tw" },
  { name: "花旗銀行土城分行", category: "金融業", domain: "citibank.com.tw" },
  { name: "合作金庫銀行 CoLab 創新實驗室", category: "金融業", domain: "tcb-bank.com.tw" },
  { name: "玉山銀行新板特區分行", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行南山廣場分行", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行台北分行", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行台大分行", category: "金融業", domain: "esunbank.com.tw" },
  { name: "玉山銀行 台中都心分行", category: "金融業", domain: "esunbank.com.tw" },
  { name: "台北富邦銀行建國分行", category: "金融業", domain: "fubon.com" },
  { name: "台北富邦銀行城東分行", category: "金融業", domain: "fubon.com" },
  { name: "上海銀行新總部大樓", category: "金融業", domain: "scsb.com.tw" },
  { name: "台北富邦銀行市府分行", category: "金融業", domain: "fubon.com" },
  { name: "王道銀行-信義威秀分行", category: "金融業", domain: "o-bank.com" },
  { name: "中國信託南港新總行", category: "金融業", domain: "ctbcbank.com" },
  { name: "中國信託土城分行", category: "金融業", domain: "ctbcbank.com" },
  { name: "中國交通銀行台北分行", category: "金融業", domain: "bankcomm.com.tw" },
  { name: "上海商業儲蓄銀行三重分行", category: "金融業", domain: "scsb.com.tw" },
  { name: "嚴宅", category: "住宅", domain: null },
  { name: "辜宅", category: "住宅", domain: null },
  { name: "張宅", category: "住宅", domain: null },
  { name: "王宅", category: "住宅", domain: null }
];
